#!/usr/bin/env bash

case "$1" in

  'sample4:generate')
    echo ""
    echo "Generating large data"
    echo ""

    src="./sample4/small"
    dest="./sample4/large"
    mkdir -p "${dest}"
    # duplicate the data to make it larger
    for i in {1..1000}; do cp "${src}/data-employment-type.csv" "${dest}/data-employment-type-$i.csv"; done
    ;;

  *)
    echo -e ""
    echo "Usage:"
    echo ""
    echo "$(tput setaf 5)    $me$(tput sgr0) $(tput setaf 3)<command>$(tput sgr0)"
    echo ""
    echo "Commands:"
    echo ""

    echo "$(tput setaf 3)    sample4:generate                           $(tput sgr0)      Generate large data for sample4"

esac
